### ISSUE TITLE
VM display/name not unique enough when in CI/branch job, suggest adding a GUID

### ISSUE THREAD

**Issue by mrysanek** [test-kitchen/kitchen-vagrant#394] opened 2019-02-07 18:45 UTC
Running on a multi-branch pipeline in Jenkins, when a PR is created against any branch Jenkins will build both the test-merged-PR and the branch that is the source of that PR.  Unless kitchen.yml was changed in that PR, the computed machine name of "kitchen-<cookbookname>-<suitename>-<platformname>" will be the same for both the branch and the test-merge-PR.  In my case, both jobs run on the same node (multiple executors).  Vagrant calls Virtualbox and the result for the second, slightly later job is:
```
ERROR warden: Error occurred: A VirtualBox machine with the name 'kitchen-pb_mini_cookbook-default-rhel-7-4-1' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```

A snip from my Jenkinsfile log:
```
2019-02-07T12:21:05.640-0600 D      Creating Vagrantfile for <default-rhel-7-4-1> (/opt/jenkins/home/workspace/b-mini-cookbook_test_manyruns_pr/pb_mini_cookbook/.kitchen/kitchen-vagrant/default-rhel-7-4-1/Vagrantfile)
2019-02-07T12:21:05.640-0600 D      ------------
2019-02-07T12:21:05.640-0600 D      Vagrant.configure("2") do |c|
2019-02-07T12:21:05.640-0600 D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
2019-02-07T12:21:05.640-0600 D        c.vm.box = "rhel-7-4-1"
2019-02-07T12:21:05.640-0600 D        c.vm.box_url = "https://[redacted]/rhel-7.4-2.1.0-x86_64-virtualbox.box"
2019-02-07T12:21:05.640-0600 D        c.vm.hostname = "default-rhel-7-4-1.vagrantup.com"
2019-02-07T12:21:05.640-0600 D        c.vm.synced_folder ".", "/vagrant", disabled: true
2019-02-07T12:21:05.640-0600 D        c.vm.provider :virtualbox do |p|
2019-02-07T12:21:05.640-0600 D          p.name = "kitchen-pb_mini_cookbook-default-rhel-7-4-1"
2019-02-07T12:21:05.640-0600 D          p.customize ["modifyvm", :id, "--audio", "none"]
2019-02-07T12:21:05.640-0600 D        end
2019-02-07T12:21:05.640-0600 D      end
2019-02-07T12:21:05.640-0600 D      ------------
```

My .kitchen.yml:
```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_url: https://[redacted]/scripts/install_chef_client_vagrant_rh7.sh
  omnibus_url: https://[redacted]/scripts
  log_level: debug

verifier:
  name: inspec

platforms:
  - name: rhel-7-4-1
    driver:
      box_url: https://[redacted]/rhel-7.4-2.1.0-x86_64-virtualbox.box

suites:
  - name: default
    includes:
      - rhel-7-4-1
    run_list:
      - recipe[pb_mini_cookbook]
```

sysinfo:
```
Red Hat Enterprise Linux Server release 7.5 (Maipo)
SSH slave of Jenkins ver. 2.150.1
Chef Development Kit Version: 3.7.23
chef-client version: 14.10.9
delivery version: master (64f556d5ebfd7bac2c0b3cc2c53669688b3ea4b5)
berks version: 7.0.7
kitchen version: 1.24.0
inspec version: 3.4.1
Vagrant 2.2.3
 -- vboxmanage --version
5.2.12r122591
 -- chef gem list kitchen-vagrant
kitchen-vagrant (1.4.0)
```

If I get time I'll create a PR (no promises unfortunately).
Thank you!

**Comment by cheeseplus** [comment] 2019-02-13 16:14
This is a good report but also a dupe of  #376 - closing it since it's the same root cause.

**Closed by cheeseplus** 2019-02-13 16:14 UTC
