### ISSUE TITLE
WSL error

### ISSUE THREAD

**Issue by lcc2207** [test-kitchen/kitchen-vagrant#401] opened 2019-05-21 15:12 UTC
Is anyone else running into this error running test-kitchen-vagrant on Windows 10 WSL

The Ubuntu image seems to work, this only seems to happen on CentOS runs.

Error:
vm:
* The host path of the shared folder is not supported from WSL. Host
path of the shared folder must be located on a file system with
DrvFs type. Host path: /root/.kitchen/cache
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1] on default-centos-7

**Comment by cheeseplus** [comment] 2019-05-21 18:19
I'd check https://www.vagrantup.com/docs/other/wsl.html. Vagrant has some things it needs to know when running in WSL. It would also be nice to get more of the log (gist is fine) but pretty sure most of this is covered by the link.

**Comment by lcc2207** [comment] 2019-05-21 18:31
I actually have all those in place and Ubuntu instance work ok, it seems to be related to the CentOS image possibly

**Comment by ksalman** [comment] 2020-05-13 22:34
@lcc2207 Were you able to find a solution?

**Comment by djessich** [comment] 2020-05-31 21:53
I have the same problem on CentOS 7 and 8. It may be solved with the solution posted at https://dracoater.github.io/2020/01/vagrant-in-WSL by adding `cache_directory: false` to `kitchen.yml`.

Although this solution is not acceptible for me, I can confirm that it works and the VM can boot. However, CentOS 7 fails with an error regarding that it fails to mount `/sysroot` and I have not found any solution yet. Maybe the kernel is too old (as it seem to work with CentOS 8 properly) or the box is broken.

**Comment by marcparadise** [comment] 2021-06-16 17:45
Closing this out - I think that the `cache_directory: false` solution is the only option here, because of the limitations inherent to vagrant under WSL.  Another workaround here might be to specify a path for the  `cache_directory` in driver configuration , providing a path that is a DrvFs  filetype. `

@djessich if the `/sysroot` mount failure is still an problem, could you open a separate issue in this repository for it?

**Closed by marcparadise** 2021-06-16 17:45 UTC

**Comment by djessich** [comment] 2021-06-25 23:48
@marcparadise It's not a problem anymore, as I switched to Ubuntu Linux. Thanks.
