### ISSUE TITLE
When used in Jenkins, can't download new version of Vagrant box

### ISSUE THREAD

**Issue by daks** [test-kitchen/kitchen-vagrant#352] opened 2018-04-16 08:13 UTC
Hello,

_I fill this issue here, but I'm not sure if it comes from test-kitchen, from kitchen-vagrant, from vagrant-libvirt, or from jenkins..._

we use kitchen-vagrant with a custom libvirt box we generate (with Packer), and which is stored on our servers. To enforce the specific box version we want to use, we define the needed option. Our kitchen config file looks like:

```
box_version: 20171109144752                                                                                                 
box_url: https://<srv.domain.tld>/<box-manifest>.json                                                                  
box_download_ca_cert: ./test/config/ca-cert.pem
```

When we generate a new Vagrant box (to keep it up to date with our config management code), we update this `box_version` and run tests in Jenkins.

But the feature of upgrading a box always fails. This is an excerpt of the output in Jenkins:

```
kitchen create <box>

-- Creating '<box>' --

-----> Starting Kitchen (v1.20.0)

-----> Creating <box>...
       Bringing machine 'default' up with 'libvirt' provider...
       ==> default: Box '<box>' could not be found. Attempting to find and install...
           default: Box Provider: libvirt
           default: Box Version: 20171109144752
       ==> default: Loading metadata for box 'https://<srv.domain.tld>/<box-manifest>.json'
           default: URL: https://<srv.domain.tld>/<box-manifest>.json
       ==> default: Adding box '<box>' (v20171109144752) for provider: libvirt
           default: Downloading: https://<srv.domain.tld>/<image>.box
      
    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
[...]
    default: Progress: 95% (Rate: 48.9M/s, Estimated time remaining: 0:00:02)
    default: Calculating and comparing box checksum...

       /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/file_checksum.rb:30:in `initialize': No such file or directory @ rb_sysopen - /srv/jenkins/.vagrant.d/tmp/box7ad909f98ba11ffcd5cd8827cecc351c917f5c45 (Errno::ENOENT)
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/file_checksum.rb:30:in `open'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/file_checksum.rb:30:in `checksum'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/box_add.rb:535:in `validate_checksum'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/box_add.rb:342:in `box_add'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/box_add.rb:273:in `add_from_metadata'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/box_add.rb:108:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builder.rb:116:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `block in run'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/busy.rb:19:in `busy'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `run'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /srv/jenkins/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_storage_pool.rb:52:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /srv/jenkins/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builder.rb:116:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `block in run'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/busy.rb:19:in `busy'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `run'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/call.rb:53:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builder.rb:116:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `block in run'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/busy.rb:19:in `busy'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `run'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/machine.rb:225:in `action_raw'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/machine.rb:200:in `block in action'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:567:in `lock'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/machine.rb:186:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/machine.rb:186:in `action'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
```

If I ssh on this Jenkins node, and with the same code, and run `kitchen create` interactively, the wanted box version is downloaded and the kitchen VM created.

I'm not sure which part of the stack causes the problem, test-kitchen? jenkins? vagrant? vagrant-libvirt? and don't know where to start digging. 
I'm open to any suggestion to find the workaround or the responsible for this bug.

**Comment by cheeseplus** [comment] 2018-04-16 12:08
This is a Vagrant problem and moreover you're several key versions behind so I'd start with trying an upgrade.

**Comment by daks** [comment] 2018-04-16 12:14
In fact, I can try to upgrade Vagrant first.
But I don't think problem comes from there, because we also use this technique (strict box_version) with Vagrant, in the same setup (jenkins, vagrant-libvirt, custom boxes...) without problem.

**Comment by daks** [comment] 2018-04-16 12:42
Using a strict version let us do the following:

- use version x.y in tests
- when needed, release a new version x.y+1
- publish this version and notify developers
- devs can't create a branch in their code to test this new version
- if it's ok, code is merged and new box is used

We previously got some problems with boxes 'not compliant', this is our workaround.

**Comment by cheeseplus** [comment] 2018-04-16 12:47
I understand _why_ one would use but in the context of Vagrant the version is most meaningful with a remote endpoint like Vagrant Cloud (which is really the only thing of it's kind). It might not hurt but it also is leaving lots of functionality on the table not to mention the primary design case.

Either way, probably nothing to do with the error and still not a kitchen-vagrant thing.

**Comment by daks** [comment] 2018-04-16 12:57
Thanks, I think I will report it at Kitchen project.

**Comment by cheeseplus** [comment] 2018-04-16 13:00
Please don't, again this has NOTHING to do with test-kitchen or kitchen-vagrant and I'll be closing any dupe issue opened on that repo (as these are both ones I maintain)

**Comment by daks** [comment] 2018-04-16 13:06
hum... are you sure?
The only possible cause might be Jenkins, but it seems weird to me.

**Comment by cheeseplus** [comment] 2018-04-16 13:17
As the developer of both test-kitchen, kitchen-vagrant, and having had a host of Vagrant issues blamed on my tooling? Incredibly sure

Vagrant is doing something bad here, the stacktrace doesn't implicate any code but Vagrant itself. Moreover when running as a Jenkins agent environmental issues can strike (i.e. interactive user vs non-interactive.).

I'm happy to try to provide assistance but thus far nothing provided implicates any of the code of either kitchen or kitchen-vagrant.

**Comment by daks** [comment] 2018-04-16 13:42
ok thanks. I had not thought about Vagrant itself, and blaming Jenkins seems weird because this kind of process is the essence of Jenkins.
Thanks for your help, I'll try to dig into this issue and report it at Vagrant project.

**Comment by cheeseplus** [comment] 2018-04-16 13:50
Did changing the version do anything to change the error? or running Vagrant in debug? what about clearing out the `~/.vagrant.d/tmp` folder?

**Comment by daks** [comment] 2018-04-16 14:14
I can't verify at the moment, but I'll asap. I'll try to upgrade Vagrant and clean tmp directory.

**Comment by daks** [comment] 2018-06-05 08:01
Hello, back with some information.

I upgraded Vagrant on my Jenkins box, I'm now running 2.1.1.
`~/.vagrant.d/tmp` has been emptied.

We created a new Vagrant box so I tried to use in a specific branch that I ran in Jenkins. The output is the following

```
-- Creating '<box>' --

-----> Starting Kitchen (v1.20.0)

-----> Creating <box>...

       Bringing machine 'default' up with 'libvirt' provider...

       ==> default: Box 'org/box' could not be found. Attempting to find and install...

           default: Box Provider: libvirt

           default: Box Version: 2018-05-25-54-gbbbcaab7

       ==> default: Loading metadata for box 'https://<srv.domain.tld>/<box-manifest>.json'

           default: URL:  https://<srv.domain.tld>/<box-manifest>.json

       ==> default: Adding box 'org/fb' (v2018-05-25-54-gbbbcaab7) for provider: libvirt

           default: Downloading: https://<srv.domain.tld>/<box-05-25-54-gbbbcaab7>.box

    default: Progress: 0% (Rate: 0*/s, Estimated time remaining: --:--:--)
    default: Progress: 13% (Rate: 44.8M/s, Estimated time remaining: 0:00:06)
    default: Progress: 28% (Rate: 45.9M/s, Estimated time remaining: 0:00:05)
    default: Progress: 43% (Rate: 46.3M/s, Estimated time remaining: 0:00:04)
    default: Progress: 58% (Rate: 46.5M/s, Estimated time remaining: 0:00:03)
    default: Progress: 74% (Rate: 46.9M/s, Estimated time remaining: 0:00:02)
    default: Progress: 89% (Rate: 47.8M/s, Estimated time remaining: 0:00:01)
    default: Calculating and comparing box checksum...

       The checksum of the downloaded box did not match the expected

       value. Please verify that you have the proper URL setup and that

       you're downloading the proper file.

       Expected: b407d291739c12664c48ac503beb66c58740d34b34cbed6232d6d5667a16ac91

       Received: 8ad063e8214e98d88e2c799d89c0caa0d06df9085a82f46f874d219a8051d73e

---- End output of vagrant up --no-provision --provider libvirt ----

Ran vagrant up --no-provision --provider libvirt returned 1] on <box>

>>>>>> ----------------------

>>>>>> Please see .kitchen/logs/kitchen.log for more details

>>>>>> Also try running `kitchen diagnose --all` for configuration

script returned exit code 1
```

As you can see, the problem is now different, it comes from checksum verification. 

What I did then : 

- on the Jenkins server, download with wget the box from the URL given in the output, and run sha256sum on the downloaded file: checksum is correct and matching the one from the json manifest file (b407d29...)
- on the Jenkins server, retrieve the Vagrantfile from `.kitchen/kitchen-vagrant/<box>`, copy it somewhere and run `vagrant up`: it successfully download the box, compare the checksum and 'install' the new box

**Comment by cheeseplus** [comment] 2018-06-05 16:58
This is still super specific to Vagrant itself, kitchen isn't munging any of the value but purely passing them through to Vagrant. The manifest itself seems like it's bad/incorrect.

**Comment by daks** [comment] 2018-06-06 07:18
The manifest itself is ok, as I can use it with Vagrant directly without problem.

**Comment by cheeseplus** [comment] 2018-06-06 21:31
Like I keep saying, that error message is coming _directly_ from Vagrant - that's not our error messaging and not our code so while I'm happy to try to help here that's not kitchen-vagrant itself throwing the error. If you can find a way to reliably reproduce this please let us know but right now there isn't anything thus far that is implicating code we control as part of this repo.

**Comment by cheeseplus** [comment] 2018-08-03 18:27
Closing this one as we've been unable to repro, feel free to open with a repo case we can validate.

**Closed by cheeseplus** 2018-08-03 18:27 UTC
Labels: Feedback Requested
