### ISSUE TITLE
hyper-v error

### ISSUE THREAD

**Issue by lcc2207** [test-kitchen/kitchen-vagrant#403] opened 2019-05-30 15:51 UTC
I have tested vagrant on WSL and with kitchen-vagrant I the following error:
I have also tested copying the Vagrant file from .kitchen/kitchen-vagrant and running vagrant up and it works ok as well.
Error:
-----> Starting Kitchen (v2.2.5)
-----> Creating <default-centos-7>...
       /root/.chefdk/gem/ruby/2.6.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:340: warning: Insecure world writable dir /c/Program Files/Oracle/VirtualBox in PATH, mode 040777
       /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/which.rb:37: warning: Insecure world writable dir /c/Program Files/Oracle/VirtualBox in PATH, mode 040777
       Bringing machine 'default' up with 'hyperv' provider...
       ==> default: Verifying Hyper-V is enabled...
       ==> default: Verifying Hyper-V is accessible...
       ==> default: Importing a Hyper-V instance
           default: Creating and registering the VM...
       An error occurred while executing a PowerShell script. This error
       is shown below. Please read the error message and see if this is
       a configuration error with your system. If it is not, then please
       report a bug.

       Script: import_vm.ps1
       Error:

       'kitchen-test1-default-centos-7-f83f5d9c-2cee-4d5d-b5d0-ffc94e291762' failed to realize. (Virtual machine ID DB2640DF-9004-4878-BEC9-D18E2B57ABCB)

       Failed to access configuration store: The file name is too long. (0x8007006F).
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider hyperv ----
STDOUT: Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
==> default: Importing a Hyper-V instance
    default: Creating and registering the VM...
STDERR: /root/.chefdk/gem/ruby/2.6.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:340: warning: Insecure world writable dir /c/Program Files/Oracle/VirtualBox in PATH, mode 040777
/opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/which.rb:37: warning: Insecure world writable dir /c/Program Files/Oracle/VirtualBox in PATH, mode 040777
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

'kitchen-test1-default-centos-7-f83f5d9c-2cee-4d5d-b5d0-ffc94e291762' failed to realize. (Virtual machine ID DB2640DF-9004-4878-BEC9-D18E2B57ABCB)

Failed to access configuration store: The file name is too long. (0x8007006F).
---- End output of vagrant up --no-provision --provider hyperv ----
Ran vagrant up --no-provision --provider hyperv returned 1] on default-centos-7
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by cheeseplus** [comment] 2019-05-30 16:07
The problem is a system level issue with the path and potentially name that kitchen generates. This requires some substantial reworking of the structure kitchen generates unique paths/names specifically for Windows based systems which is the only place we hit path length restrictions.

**Comment by Xorima** [comment] 2019-08-02 14:30
Opened #404 which should resolve this error

**Comment by tas50** [comment] 2019-08-06 16:18
This is fixed in the latest release. Thanks for the report @lcc2207

**Closed** 2019-08-06 16:18 UTC
